# Generated by Django 4.2.16 on 2024-09-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_project", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
