# Generated by Django 4.2.16 on 2024-09-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_project", "0005_alter_product_category_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
