# Generated by Django 4.2.16 on 2024-09-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_project", "0007_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
