# Generated by Django 4.2.16 on 2024-09-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_project", "0008_alter_category_name_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
