# Generated by Django 4.2.16 on 2024-10-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_project", "0010_searchhistory_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
