# Generated by Django 4.2.16 on 2024-10-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_project", "0011_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
